package store

import (
	"context"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Backup writes a consistent snapshot of the database into dir (via
// VACUUM INTO) and keeps only the most recent `keep` snapshots.
func (db *DB) Backup(dir string, keep int) (string, error) {
	if err := os.MkdirAll(dir, 0700); err != nil {
		return "", err
	}
	name := filepath.Join(dir, "commit-"+time.Now().Format("2006-01-02-150405")+".db")
	// Filename is generated by us; quote-escape defensively for the SQL literal.
	if _, err := db.conn.Exec("VACUUM INTO '" + strings.ReplaceAll(name, "'", "''") + "'"); err != nil {
		return "", err
	}
	pruneBackups(dir, keep)
	return name, nil
}

func pruneBackups(dir string, keep int) {
	entries, err := filepath.Glob(filepath.Join(dir, "commit-*.db"))
	if err != nil || len(entries) <= keep {
		return
	}
	sort.Strings(entries) // timestamped names sort chronologically
	for _, old := range entries[:len(entries)-keep] {
		os.Remove(old)
	}
}

// BackupLoop takes a snapshot shortly after startup, then once a day until ctx
// is cancelled. Failures are logged, never fatal.
func (db *DB) BackupLoop(ctx context.Context, dir string) {
	const keep = 7
	timer := time.NewTimer(2 * time.Minute) // let things settle before the first one
	defer timer.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-timer.C:
			if path, err := db.Backup(dir, keep); err != nil {
				log.Printf("backup error: %v", err)
			} else {
				log.Printf("backup written: %s", path)
			}
			timer.Reset(24 * time.Hour)
		}
	}
}
